vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    voiture_image:
      uri_prefix: /front/images/voitures
      upload_destination: "%kernel.project_dir%/public/front/images/voitures"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
          

